
version: 2

models:
  - name: hubspot_contacts_clean
    description: "A starter dbt model"
    columns:
      - name: vid
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: canonical_vid
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: seed_clean
    description: "A starter dbt model"
    columns:
      - name: a
        description: "The primary key for this table"
        tests:
          - not_null

